### ISSUE TITLE
Burlap as a viable book-binding material in Mystcraft

### ISSUE THREAD

**Issue by freyquency** [squeek502/VeganOption#10]
I'm not sure how it's added but it'd be cool if burlap could be used in place of leather in the book binder and link book recipes.

**Comment by squeek502** [comment]
Good idea, will look into it.

**Comment by squeek502** [comment]
Quite a bit more difficult than I expected. Kept finding more and more places where `itemStack == Items.leather` was hardcoded in the Mystcraft code :disappointed:

**Comment by squeek502** [comment]
@erima here's a build with this code in it if you want to test it out: [VeganOption-mc1.7.10-0.1.0-mystcraft-test.jar](http://www.ryanliptak.com/misc/VeganOption-mc1.7.10-0.1.0-mystcraft-test.jar)

Let me know if there's anything else for which the VO alternatives aren't working in Mystcraft.

**Comment by freyquency** [comment]
Ah, thanks for looking into it! I just tried out the test.jar and it seems to work great. The other item that stuck out to me was black ink.  It's kind of an odd combo - I like your implementation of black ink but it also can be used to make ink vials, which is in the Fluid Registry as black ink. Perhaps a convenient way to approach it would be to consider VO black ink to be a smaller mb of ink than a vial (though the name implies the opposite). 

I'm not implying that you should change yours or not, just pointing out that it may be confusing, and that I'd also +1 any kind of fluid registry additions for VO liquids. Soap ocean worlds!
