### ISSUE TITLE
Composter haunted

### ISSUE THREAD

**Issue by freyquency** [squeek502/VeganOption#13]
Just noticed the composter is spinning on it's own, constantly. Still spins after emptying it. Breaking and replacing it stops spinning, but spinning it again causes it to endlessly spin. I've used it quite a bit and it hasn't done it before.

Edit: Scratch that, it seems to stop spinning after breaking it and placing it down again. Still not sure what caused it to endlessly spin.

**Comment by squeek502** [comment]
Haha, that's very strange. Seems like somehow the composter's lastAeration field got set to some time in the future. I'll add some protection against the infinite spinning, but I'm not sure what would have caused the time traveling lastAeration field.
