### ISSUE TITLE
Add dispenser support for bottled fluids

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#15]
Ink and vegetable oil fluids should be placeable by dispensers. Soap solution already has a dispenser behavior, so it's not applicable.

**Comment by jawsawn** [comment]
Soap fluid is the best fluid in the whole modded history. It deserves to be placed on ground!

**Comment by squeek502** [comment]
I should be able to make soap solution placeable by adding a bucket version of it. That way, you could craft soap solution using piston crafting (or fill a tank using a bottle of soap solution) and then pick it up using a bucket, which would allow you to place it back down wherever you want.

I really need to get back to working on this mod. There's a lot that I worked on a while back but never quite finished up.
