### ISSUE TITLE
[Bug] Frozen bubble turns into ender pearl in ANY liquid

### ISSUE THREAD

**Issue by jawsawn** [squeek502/VeganOption#17]
Isn't it supposed to only turn into ender pearl on liquid ender?

**Comment by squeek502** [comment]
Right. Fixed by https://github.com/squeek502/VeganOption/commit/b5c6d1a4fe7233d1bbf0dd251def076d2b79faa9 but I haven't released a new version yet.

**Comment by jawsawn** [comment]
That was a game breaker bug. release new verse asap, also I would suggest that disable mashed potato CRAFTING recipe with the piston by default (still let it available on configs). You gotta be brave with the new features. (the point it to force players to make auto piston smasher by themselves)
