### ISSUE TITLE
In-world crafting option for vegetable oil

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#3]
Not really sure how best to pull this one off, but it'd be nice to have in-world crafting alternatives for most things added by the mod.

**Comment by freyquency** [comment]
Was just thinking - maybe the piston dynamic you use for potatoes, over ice, could be part of it. Inspired by [this cold-pressing How it's Made](https://www.youtube.com/watch?v=qKrY_WjogXk).

**Comment by squeek502** [comment]
Yeah, I'd like to use the same piston method, but the trouble is that the output is a fluid (or a bottled fluid), which makes it somewhat difficult, as the fluid block can't be placed if the piston is extended (or, if bottled, where does the bottle come from)?

Perhaps, I could do something like:
- Piston extends and crushes a vegetable oil source
- One vegetable oil source gets consumed and transformed into a byproduct (seed cakes/plant slurry/something like that)
- This byproduct uses a special EntityItem and holds the coordinates of where the fluid block should be put once it's possible, and continually checks until the block can be placed (the piston retracts)

I'm not sure if the byproduct would be worth it, but I think it'd help. I could also store the coordinates in the chunk data or something like that, I guess.

Perhaps also I could force the piston to retract once it crushes a vegetable oil source and then "schedule" the fluid block placement.

EDIT: Or, I guess, the output could be the fluid block as an item, but I'm not sure there's any other mods that do that and it seems pretty weird.

**Comment by freyquency** [comment]
In regard to the "Where does the bottle come from?" maybe just leave it as a fluid? A dispenser with an empty bucket could do automation if the player wanted it. Perhaps, going back to the ice thing I mentioned (a Minecrafty "cold press") the pressing of the vegetable oil source combined with the ice underneath melts the ice into oil instead of water?

**Comment by squeek502** [comment]
Ideally I'd like to leave it a fluid; my point was that having the output be an item makes implementing it very simple, but it doesn't really work in this case because of the bottle.

Simply turning the ice into vegetable oil might be a good option.

**Comment by squeek502** [comment]
So, what I've decided to do is require a fluid handler (tank, drum, etc) below the piston head to catch the fluid output.

The only downside is that VO doesn't add a fluid handler, so it'd rely on other mods for this in-world crafting to be possible. I'm not sure if I should add a basic tank-like block to VO for this purpose or if relying on other mods in this way would be okay. Let me know what you think, @erima.

Note also that this will also work for plant milk (see #4), but the piston will need to both displace a water block and crush 2 plant milk source items + sugar for it to work.

**Comment by freyquency** [comment]
Hm. What about the cauldron? Could you drop fluid in it?

**Comment by squeek502** [comment]
The cauldron is utter garbage. It'd need a complete rewrite for it to have any potential uses. I originally wanted to use the cauldron for this type of crafting, but it simply isn't feasible, unfortunately.

**Comment by freyquency** [comment]
Hm, what about a press into a brewing stand? Use the bottles in the bottom, item in the top, a press above? Not exactly in-world but it seems like your goal is to keep a lot of these things self-contained to VO in the long run. Aside from creating a storage container of some sort it seems like having support for other mod tanks is good, but not self-contained.

**Comment by squeek502** [comment]
Using a brewing stand like that seems a bit weird.

I'm pretty much set on the fluid tank solution, and have it nearly finished (just need to finish up the NEI handler for piston recipes).

If I add a fluid tank, I could make it get automatically filled by finite liquids that flow into them (aka raw ender). That way, it'd have an internal purpose, it'd enable this type of crafting in a self-contained way, and it'd be (slightly) unique.
