### ISSUE TITLE
Compost: Add support for various modded farmland blocks

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#32]
From MCF:

> Does compost work when connected to Extra Utilities' fertilized dirt, rather than vanilla farmland?

Relevant code: https://github.com/squeek502/VeganOption/blob/master/java/squeek/veganoption/blocks/BlockCompost.java#L46

Should turn the Blocks.farmland check into a farmlandBlocksList.contains check and add various modded blocks to that list in the relevant mod integration handlers.

**Comment by ghost** [comment]
Correction: I had said Extra Utilities, but it's actually with the Random Things mod.

And I'll take your word on that; programming standards left me behind when they went from Procedural to Object-Oriented.
