### ISSUE TITLE
FluidIdRegistryMessageHandler exception when joining server

### ISSUE THREAD

**Issue by gioporta** [squeek502/VeganOption#34]
When joining my multiplayer server, I get a message saying "A fatal error has occurred, this connection has been terminated."

Here is a snippet from my fml-client-latest.log file: http://pastebin.com/0xh3u6gg

It seems to throw "java.lang.IllegalArgumentException: value already present: veganoption.someliquid" every time I attempt to join the server. Removing the mod gets rid of the problem.

This is present using Forge 1448 on 1.7.10 and Java 1.8.0_40 even when it is the only mod installed.
- When running the server on Windows, or in singleplayer, this issue is nonexistent.
- It has occurred on my Linux VPS (CentOS) and 2 different shared Minecraft hosts.

**Comment by squeek502** [comment]
Looks like this was caused by https://github.com/MinecraftForge/MinecraftForge/issues/1973

For anyone that runs into this in the future: upgrade to Forge version 1490 or above.
