### ISSUE TITLE
Add consistent form of resin collection

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#38]
http://minecraft.curseforge.com/projects/the-vegan-option?comment=4

See https://github.com/squeek502/VeganOption/issues/30

> Resin: See [this issue](https://github.com/squeek502/VeganOption/issues/30) if you're using Treecapitator. I do really like the Electrical Age implementation of resin (shown in the linked issue), though, so I might end up doing something similar to make it more consistent.

**Comment by PearlCanopus** [comment]
I see Thermal Expansions Arboreal Extractor (TE for 1.1x.x).
I see no restriction to cover this with a balanced low tec variant. But Resin needs to be unified for mod interaction.

https://www.reddit.com/r/feedthebeast/comments/60rwr2/breaking_the_new_arboreal_extractorsfor_science/
