### ISSUE TITLE
Add a single inventory slot to plastic eggs

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#45]
Just a bit of fun that I thought about a while back but never implemented. 

When thrown, they will drop the item inside as they explode.

**Comment by Sunconure11** [comment]
What if shoving gunpowder inside of it causes a small explosion?

And shoving blaze powder inside lights a fire.

Maybe they could be dyed and disguised as normal eggs. Perhaps potions shoved inside (splash, and if Et Futurum is installed, lingering) could apply their effects on impact. A rather weird, but, inconspicuous form of hiding potions.

**Comment by elifoster** [comment]
Closed by #74 and 6920ac2c47d9279659bffbecf8a00a2b5591cc84. There are some more modifiers that could be implemented but since the modifier API's been implemented this issue can be closed.
