### ISSUE TITLE
Weirdness with beds

### ISSUE THREAD

**Issue by Sunconure11** [squeek502/VeganOption#46]
So I'm in a server that has this mod, and I stumbled upon the following bugs with straw beds:
1. https://www.dropbox.com/s/tkww9rvl8ah6n8g/Screenshot%202015-11-17%2020.43.59.png?dl=0
2. You cannot leave beds unless you press ESC.

**Comment by squeek502** [comment]
Appreciate all the feedback you've been providing. Will look into this. 

Checks for the Minecraft bed must be hardcoded in the Minecraft code for rendering or something, because [I basically re-use all of the BlockBed code with as few changes as possible](https://github.com/squeek502/VeganOption/blob/master/java/squeek/veganoption/blocks/BlockBedGeneric.java).

**Comment by squeek502** [comment]
1. Can't see what could be causing this. Not sure how to test it on my own, either, as it looks like I need two Minecraft accounts to run two dev clients now
2. Can't reproduce this. The _Leave Bed_ button shows up for me and works fine.

I did notice that leaving a bed before actually sleeping will still do damage, which is not intended, though. (EDIT: Fixed this in 8ef7fcccf2dec1e30595d521a93eef503475084b)

**Comment by Sunconure11** [comment]
Sorry, what I meant to post about the leave bed button button was that it shows up, its just that pressing it does nothing.

Keep in mind this happened on a server.

**Comment by squeek502** [comment]
Leave Bed worked for me on a local server as well.

**Comment by squeek502** [comment]
Yeah, just tried again to make sure and was still unable to reproduce the Leave Bed issue. Would it be possible to send me the mod pack you are using so I can see if it's a mod interaction problem?

**Comment by Sunconure11** [comment]
Check Compitum Magia on technic. It's happening with normal beds too

**Comment by Sunconure11** [comment]
The pack is one I helped build so I can fix this easily once sorted out

**Comment by squeek502** [comment]
Seems to be unrelated to this mod. The problem still exists after removing VO from the modpack and trying to sleep in a normal bed.

No clue which mod would be causing it.

**Comment by squeek502** [comment]
@Sunconure11, I was curious so I did some testing and found which mod is causing this. It is `liteloader-1.7.10.jar`. Removing that should fix the bed issues.
