### ISSUE TITLE
Plastic Star

### ISSUE THREAD

**Issue by Fortanono** [squeek502/VeganOption#48]
So, if my Charred Trees idea goes through, we won't have more than one use for Bioplastic. So, my idea for the Nether Star would be this: First, you make a Plastic Star with 5 Plastic in an X shape. Now, you need Souls. To get these, you need Soul Glass (smelted from Soul Sand). Break the Soul Glass to get 2-4 Souls (increased with Fortune). Then, make 5 Soul Blocks, each with 9 Souls. Smelt one into a Refined Soul Block, and that the center of a plus shape that you make with these. Drop the Plastic Star on the Refined Soul Block. A hologram will appear asking for four of these Nether ingredients in a random order: Nether Wart, Blaze Powder, Glowstone Dust, Nether Quartz, or a Soul. Throw each of these onto the four Soul Blocks, and watch as your Plastic Star becomes a Nether Star.

**Comment by squeek502** [comment]
Nether star alternative suggestions should go here: https://github.com/squeek502/VeganOption/issues/1

Note that I don't really like the idea of it being craftable, no matter how complicated the crafting recipe is.
