### ISSUE TITLE
White Vegetable Oil Ink should be made with Saltpeter

### ISSUE THREAD

**Issue by Fortanono** [squeek502/VeganOption#51]
Nether Quartz seems a bit too expensive for white dye, as you need to go to the Nether for it. I think saltpeter would fit, what do you think?

**Comment by squeek502** [comment]
Fair enough. Nether quartz was kind of just a "it's white-ish so I guess that works" sort of thing because vanilla Minecraft doesn't have a source of white pigment (titanium, lead, zinc, lime/chalk).

**Comment by Sunconure11** [comment]
Saltpeter IRL cannot be used to make dye. Why not some other pigment in the overworld?

**Comment by Sunconure11** [comment]
https://en.wikipedia.org/wiki/List_of_inorganic_pigments#White_pigments

**Comment by squeek502** [comment]
@Sunconure11, any suggestions for which white pigment should be added and how? I couldn't figure out how to do it without adding something to worldgen.

**Comment by Sunconure11** [comment]
Why not have it obtained in a fashion similar to mining sulfur and saltpeter, except from stone? To compensate, it should be fairly rare. 

Or even a process something like this: https://en.wikipedia.org/wiki/Zinc_oxide#Production

**Comment by squeek502** [comment]
While I think adding drops to other blocks is an okay solution, I don't want to overdo it, and stone already has a rare drop of bones. I also would like to avoid adding something that is only used for a single recipe and has little use outside of that.

Would it be acceptable to keep the current nether quartz recipe as the only recipe when VO is installed on its own, and then rely on other mods to supply other, easier, forms of white pigment (titanium/zinc/lead/etc)?

**Comment by Sunconure11** [comment]
That could work. You could try maybe oxeyes or some other white flower.

**Comment by Fortanono** [comment]
Okay, maybe I'm late to the party here, but Titanium/Zinc could be a drop from Iron Ore... now to find another use for it. Maybe it could be used in the crafting of Encrusted Obsidian?

**Comment by Sunconure11** [comment]
That might be a good idea.

**Comment by reteo** [comment]
Correct me if I'm wrong, but isn't white dye technically bleach?  Most real-world whitening materials tend to be things that remove color, rather than add white.  Perhaps add a recipe for hydrogen peroxide?

**Comment by ghost** [comment]
Instead of coming up with a recipe to make white dye, would it be possible to just come up with some kind of bleach recipe, which can then be used on existing dyes to make them white?  Maybe use redstone as a recipe for some crude electrolysis tech to produce hydrogen peroxide from water and air?

H2O (Water) + 2O2 (2 molecules of Air) ---> H2O2 (Hydrogen Peroxide) + O3 (Ozone)

The end result is hydrogen peroxide, as well as a temporary sense of nausea (recognizable to anyone who ever smelled ozone).

**Comment by Sunconure11** [comment]
I like idea of Titanium or Zinc being drops from ores rarely.

**Comment by elifoster** [comment]
White ink has been removed in the latest version, commit 344a1db4511ed3a2b0c0d0060fe5477f9edba551, due to vanilla adding 3 methods of getting white dye besides killing skeletons - using their composter to make bone meal, mining fossils in the nether, and the lily of the valley flower.
