### ISSUE TITLE
Crash when sleeping

### ISSUE THREAD

**Issue by HeroOfChaos** [squeek502/VeganOption#65]
Hello,
I'm using the LitW Renaissance mod pack that includes an older version of this mod. I tried to update it to the most recent beta (0.2.0) and the game crashes when I go to sleep.
Here are the server and client crash reports that were created. Maybe you can do something with them.
Reverting to the original version in the mod pack (0.1.1) works.
[crash-2016-06-04_21.43.28-server.txt](https://github.com/squeek502/VeganOption/files/299002/crash-2016-06-04_21.43.28-server.txt)
[crash-2016-06-04_21.43.32-client.txt](https://github.com/squeek502/VeganOption/files/299003/crash-2016-06-04_21.43.32-client.txt)

**Comment by squeek502** [comment]
You need a more recent Forge version than what LitWR uses. I forget the exact minimum Forge version, but any recent version would work. Not sure how you would go about updating Forge for LitwR, though.

**Comment by HeroOfChaos** [comment]
Thanks!
Yeah, updating forge is quite a hassle, but I already had to do it for another mod I installed. I'll see what I can do.
