### ISSUE TITLE
NoClassDefFoundError: squeek/veganoption/blocks/BlockJutePlant

### ISSUE THREAD

**Issue by Limewood** [squeek502/VeganOption#73]
The 1.10.2 branch crashes on loading, because it can't find BlockJutePlant, which seems to be caused by not finding mcjty.theoneprobe.api.IProbeInfoAccessor.
This is without any other mods.

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ASMPlugin (VeganOption-mc1.10.2-1.10.2.jar)
> Contact their authors BEFORE contacting forge
> 
> // Everything's going to plan. No, really, that was supposed to happen.
> 
> Time: 2017-02-11 15:22
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Vegan Option (VeganOption)
> Caused by: java.lang.NoClassDefFoundError: squeek/veganoption/blocks/BlockJutePlant
> 	at squeek.veganoption.content.modules.Jute.create(Jute.java:73)
> 	at squeek.veganoption.content.ContentModuleHandler.preInit(ContentModuleHandler.java:61)
> 	at squeek.veganoption.VeganOption.preInit(VeganOption.java:34)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: squeek.veganoption.blocks.BlockJutePlant
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 40 more
> Caused by: java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/IProbeInfoAccessor
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 42 more
> Caused by: java.lang.ClassNotFoundException: mcjty.theoneprobe.api.IProbeInfoAccessor
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 46 more
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 48 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Linux (amd64) version 4.8.0-37-generic
> 	Java Version: 1.8.0_121, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 143192720 bytes (136 MB) / 357720064 bytes (341 MB) up to 2134114304 bytes (2035 MB)
> 	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2221 5 mods loaded, 5 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
> 	UCH	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
> 	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
> 	UCE	VeganOption{1.10.2} [The Vegan Option] (VeganOption-mc1.10.2-1.10.2.jar) 
> 	Loaded coremods (and transformers): 
> ASMPlugin (VeganOption-mc1.10.2-1.10.2.jar)
>   squeek.veganoption.asm.ClassTransformer
> 	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 367.57' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by squeek502** [comment]
Hm, thought we protected ourselves from this. Will look into it, thanks for the report.
