### ISSUE TITLE
Raw Ender not craftable

### ISSUE THREAD

**Issue by ghost** [squeek502/VeganOption#76]
It says you can craft Raw Ender when you let flow water in the night time to an Ender Rift. The FTB-Wiki says it it is a Multiblock, so I built four blocks of Encrusted Obsidian with a gap in the middle:
EO AIR EO
EO AIR EO

But nothing happens, the Multiblock does not become active.

**Comment by elifoster** [comment]
That template is at angle. From the top, it should look like: (encrusted obsidian: E)
_E
E_E
_E

**Comment by ghost** [comment]
Thanks, then the entry in the wiki is wrong.

**Comment by elifoster** [comment]
It isn't wrong, it's just a trade off of the multiblock template that small structures aren't that clear.

**Comment by elifoster** [comment]
By the way, I've replaced the template with an image so hopefully it's a bit clearer now.
