### ISSUE TITLE
Idea: Mod Integration Thermal Foundation

### ISSUE THREAD

**Issue by PearlCanopus** [squeek502/VeganOption#82]
It would be great to see optional recipes for Thermal Foundation mob drops:

- Resonant Ender (refining of "Raw Ender")
- Blizz Rod
- Blitz Rod
- Basalz Rod

The black ink recipe was quite hard compared to fast squid farming. Maybe there is a way to use (char)coal dust/powder, if available by mod or add a manual mill block and some dusts by yourself.
So you could also produce and use sawdust.

**Comment by elifoster** [comment]
Do you have any ideas for creating the Resonant Ender, Blizz Rod, Blitz Rod, and Basalz Rod? I'm not really familiar with Thermal Foundation as I never really liked the CoFH mods.

**Comment by PearlCanopus** [comment]
The mobs represent the elements.
Blaze = fire
Blitz = air
Blizz = water (ice)
Basalz = earth

I'd like to create suggestions for within the next few days.

**Comment by PearlCanopus** [comment]
- Blitz Rod: plastic rod + redstone dust + rosin + saltpeter
- Blizz Rod: plastic rod + redstone dust + rosin + snowball
- Basaltz Rod: plastic rod + redstone dust + rosin + sulfur

**Comment by PearlCanopus** [comment]
Resonating Ender:

Ender Pearl to Resonating Ender has a 4:1 ratio. 4 buckets/basins Raw Ender will result in 1 bucket/basin Resonating Ender.

I could imagine to surround raw ender fluid or basins by magma blocks (Vanilla 1.10.+).
Maybe TVO-basins can accept a tenth, fifth, quarter bucket or 100/200/250/500 MilliBuckets. Would make a recipe easier to proceed.
If there's a problem with parts of a bucket volume, you could make the "Magmablock Tank" a heighth of 4 (16 blocks needed at least). When the process finished the fluid can run into a basin below.
The converting need a few moments.
Else "Magma Frame/Rift" could be placed below the Ender Rift. But this would need the basin accept Millibuckets.

Another not that cool way with crafting table could be:
4 Buckets Raw Ender + 5 Magma Cream result in 1 Bucket of Resonating Ender + 3 empty buckets.

**Comment by squeek502** [comment]
Good ideas, I like them.

The basin can hold any amount up to 1 full bucket, so it would indeed be possible to convert 1 bucket to 1/4 bucket. It seems like there might be a more elegant method of implementing the resonant ender recipe, but I'm not sure (dropping certain items in a basin filled with raw ender, cauldron style?)

**Comment by squeek502** [comment]
Partially addressed by https://github.com/squeek502/VeganOption/commit/68d0d9b3c812c026c038ff4010c37582f8e13473, still not totally sure how to handle resonant ender. It's worth noting that it is already possible to get from raw ender to resonant ender with Thermal Expansion installed (Raw Ender -> Ender Pearl -> normal TE stuff).

**Comment by elifoster** [comment]
I don't think the Resonant Ender thing is that important to have a direct conversion for because it's already possible indirectly.

**Comment by squeek502** [comment]
Agreed, and there's not really an obvious solution. Considering this done for now.
