### ISSUE TITLE
[1.10.2] UniversalBucket behaving strangely with OreDict / JEI

### ISSUE THREAD

**Issue by squeek502** [squeek502/VeganOption#87]
Because the universal bucket uses NBT to differentiate types, adding one of our buckets to an ore dictionary entry means that it seems to have some weirdness when added to oredict (in this case, `listAllmilk` for plant milk). The strange thing is, this ~~doesn't actually seem to affect recipe usage~~, but the oredict shows up in OreDictTips for all universal buckets.

Also, weird things are happening with regards to the JEI usage/crafting stuff in VO, where the entries of buckets are combined in weird ways.

**Comment by elifoster** [comment]
This sounds like it might be an issue within Forge's OreDictionary implementation rather than on our end but I'd have to look into it a bit more. Could also just be an issue with OreDictTips although that mod is extremely simple so it's doubtful.

**Comment by squeek502** [comment]
I was wrong about the effects--it actually does affect recipes (Raw Ender Bucket works in recipes that take a Plant Milk Bucket [as well as any other Universal Bucket instance, including from other mods]) but it doesn't show up in JEI, so OreDictTips is right and JEI just obscures the effects.

OreDictionary has no concept of NBT in any of its checks/hashes/etc, so we might need to drop the Universal Bucket for things we want to add to the Ore Dictionary.

**Comment by elifoster** [comment]
See also MinecraftForge/MinecraftForge#4165
