### ISSUE TITLE
Jute/high farn drops itself while farming 

### ISSUE THREAD

**Issue by Dadidus** [squeek502/VeganOption#91]
![2017-11-27_15 51 40](https://user-images.githubusercontent.com/34032661/33272576-dc0b4220-d38a-11e7-9702-fe634fb8968d.png)
![2017-11-27_16 00 25](https://user-images.githubusercontent.com/34032661/33272995-3feb10c6-d38c-11e7-94a3-962eec8fdee8.png)
When I plant jute seeds the plant grows normaly, but when its full grown it drops randomly.
Minecraft:            1.11.2
Forge                   13.201.2530
Vegan Option:     1.1.0 (1.1.0)

**Comment by squeek502** [comment]
@BasketThyme this is probably about your forked version. It'd be good if you could turn on issue reporting on your repository.
