### ISSUE TITLE
Status and future of 1.20 port

### ISSUE THREAD

**Issue by elifoster** [squeek502/VeganOption#92]
Paging @squeek502

I've just about got the mod ported to MC 1.20 on the 1.20 branch. Just a couple feature modules left to get working properly. I know you're not involved in modded MC anymore but I'd like to know how you'd prefer it be handled. Obviously it's public domain so I could just fork it and call it "Vegan Option 2" or some shit like that, but personally I think it would be good to be able to keep the repo's issue tracker and PR history and also keep it tied to the original creator and the original mod. Design-wise I'm intending on keeping it true to the original mod, and code-wise it's still pretty much the same as it was before, although a few things had to be rewritten (the recipe stuff, mostly).

To me the options for the repo seem to be the following:
- I fork the repo. This would probably be easiest, but would lose all the issue history, balance and feature discussions etc., and PR history on this repository.
- I continue working on this repository, and the default branch is changed to a `latest` branch or something along those lines from the `1.20` branch so that never needs to be changed again (as far as I can tell, setting the default branch is the only permission that could cause an issue if I were to simply keep working on the mod on this repository). This would be the preferred option in my opinion.
- The repository is transferred to either an organization with both of us or to me. This would break old links and local clones. Not to mention this is your original creation. Not really ideal.

And as for the name and "brand" (if you wanna call it that) of the mod, I would personally rather it just stay "The Vegan Option", since again the codebase is basically the same and from a game design perspective it is still basically the same. But if you'd rather it be under a new name since you no longer work on it, that's also fine by me. It's all good.

Hope you've been doing well these past few years.

**Comment by squeek502** [comment]
Whatever you want to do I'm totally okay with; happy to see this continued and I have full trust that whatever you want to do with it will be great. Let me know if there are any permissions you're missing.

- Continuing on this repo sounds good to me
- Feel free to change the default branch and structure the repo however you'd like
- Keeping the name the same seems good to me

It seems like you are avoiding CurseForge these days, but if you want to release the new version [there](https://www.curseforge.com/minecraft/mc-mods/the-vegan-option) as well let me know and I'll give you full permission over that project, too.

**Comment by elifoster** [comment]
Personal repo permissions unfortunately can't be changed granularly as far as I know. But I think the only thing I would need is the default branch changed. I have unstaged local changes on 1.20 right now, but once I get those pushed I'll rename the branch to `latest` and then once that's done you can change the default branch to that.

As for CurseForge: I think I'm able to push versions and change the description on CurseForge already, although you're right I have been avoiding it. I've been putting my mods on Modrinth. I'll probably just update the description to link to the Modrinth page -- I had already been moving my mods over just because it's a better service imo, when it came out that Overwolf, CurseForge's owner, is fundraising to "assist [Israel's] war effort". That pretty much sealed it for me.

**Comment by elifoster** [comment]
Since 1.20 is now the default branch, do you mind renaming it to "latest"? Only repository owners can rename the default branch.

**Comment by squeek502** [comment]
Done

**Comment by elifoster** [comment]
Thanks
